---
- name: Ensure destination for compose file exists
  file:
    path: "{{ docker_compose_generator_output_path }}"
    state: directory
    owner: "{{ docker_compose_generator_uid }}"
    group: "{{ docker_compose_generator_gid }}"
- name: Write docker-compose file for each service
  include_tasks: gen-compose.yml
  loop: "{{ services }}"